### ISSUE TITLE
Luna Studio installation leaves garbage in C:\tmp

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna-manager#206]
![obraz](https://user-images.githubusercontent.com/1548407/47014834-aa9d7b80-d14b-11e8-8f8c-5a6af33d8c86.png)

The temporary files should be removed when installer closes.

**Comment by sylwiabr** [comment]
This should've been fixed by: https://github.com/luna/luna-manager/pull/213

**Comment by mwu-tow** [comment]
It is not fixed from what I see. The files are just left now in another directory (now the correct `%TEMP%`). This report is not about wrong temp location, it is about not removing files from temp.
